---
bibliography: manuscript.bib
csl: systematic-biology.csl
site: "bookdown::bookdown_site"
output:
  bookdown::pdf_document2:
    toc: FALSE
---

```{r setup, include=FALSE}
	# Load packages
	## General
library(knitr)
library(tidyverse)
library(reshape2)
	## Graphics
library(FactoMineR)
library(factoextra)
	## Biological
library(vegan)
library(ape)
library(phangorn)
library(phytools)
library(OUwie)
library(picante)
library(geiger)
library(phylobase)
library(fields)
library(phylosignal)
library(geomorph)
library(phylopath)
library(Rphylip)
library(arbutus)

	# Configure knitr, see http://yihui.name/knitr/options
	opts_knit$set(
	  progress=TRUE,
	  verbose=TRUE)
	opts_chunk$set(
	#  include=FALSE,
	  cache=TRUE,
	  echo=FALSE,
	  message=FALSE
	 )
	# Set paths to input data
	setwd("~/tentilla_morph")
	
	#Load raw data
  read.csv("byslide.csv") -> numbers
  categorical <- read.csv("Homolog_Categorical.csv")[,-2]
  rownames(categorical) = categorical$Species
  
  #Polish fields
  castnumbers = numbers
  castnumbers[castnumbers=="needDIC"] <- NA
  castnumbers[castnumbers=="needConfocal"] <- NA
  castnumbers[castnumbers=="needMature"] <- NA
  castnumbers[castnumbers=="needReslide"] <- NA
  castnumbers[castnumbers==-1] <- NA
  castnumbers[,c(-1,-2,-3)] <- sapply(castnumbers[,c(-1,-2,-3)],as.character)
  castnumbers[,c(-1,-2,-3)] <- sapply(castnumbers[,c(-1,-2,-3)],as.numeric)
  
  #Define functions to deal with NAs and decimals
  mean.na <- function(a){mean(a, na.rm = TRUE)}
  var.na <- function(a){var(a, na.rm = TRUE)}
  round3 <- function(a){round(a, 3)}
  
  #Compute morphometric ratios
  coiledness = castnumbers$Cnidoband.free.length..um./castnumbers$Cnidoband.length..um.
  heteroneme_elongation = castnumbers$Heteroneme.free.length..um./castnumbers$Heteroneme.width..um.
  haploneme_elongation = castnumbers$Haploneme.free.length..um./castnumbers$Haploneme.width..um.
  desmoneme_elongation = castnumbers$Desmoneme.length..um./castnumbers$Desmoneme.width..um.
  rhopaloneme_elongation = castnumbers$Rhopaloneme.length..um./castnumbers$Rhopaloneme.width..um.
  heteroneme_shaft_extension = castnumbers$Heteroneme.free.length..um./castnumbers$Heteroneme.shaft.free.length..um.
  Heteroneme_to_CB = castnumbers$Heteroneme.free.length..um./(castnumbers$Cnidoband.free.length..um.+0.001)
  total_heteroneme_volume = castnumbers$Heteroneme.volume..um3.*castnumbers$Heteroneme.number
  total_haploneme_volume = (castnumbers$Cnidoband.free.length..um./castnumbers$Haploneme.width..um.)*((4*pi/3)*0.5*castnumbers$Haploneme.free.length..um.*((0.5*castnumbers$Haploneme.width..um.)^2))
  cnidomic_index = log(total_heteroneme_volume + total_haploneme_volume)
  cnidomic_index[which(is.na(cnidomic_index))] <- log(total_haploneme_volume[which(is.na(cnidomic_index))])
  cnidomic_index[which(is.na(cnidomic_index))] <- log(castnumbers[which(is.na(cnidomic_index)), "Heteroneme.volume..um3."])
  cnidomic_index[cnidomic_index==-Inf]<-NA
    morphometrics = data.frame(castnumbers$slide_id, castnumbers$Species,coiledness, heteroneme_elongation, haploneme_elongation, desmoneme_elongation, rhopaloneme_elongation,heteroneme_shaft_extension, Heteroneme_to_CB, total_heteroneme_volume, total_haploneme_volume, cnidomic_index)
  names(morphometrics)[1:2] = c("slide_id"," Species")
  castnumbers = data.frame(castnumbers,morphometrics[,c(-1,-2)])
  
  #logtransform variables which are not normal
  castlogs = castnumbers
  non_normal = apply(castnumbers[,c(-1,-2,-3)], 2, shapiro.test) %>% lapply(function(x){x$p.value}) %>% unlist() 
  non_normal = which(as.vector(non_normal) < 0.05)+3
  castlogs[,non_normal] <- sapply(castnumbers[,non_normal], log)
  castlogs[castlogs==-Inf]<-NA
  
  #Means, varinces, standard errors
  castmeans <- aggregate(. ~  Species, data = castnumbers[,c(-1,-3)], mean.na, na.action = na.pass)
  castmean_logs <- aggregate(. ~  Species, data = castlogs[,c(-1,-3)], mean.na, na.action = na.pass)
  castvariances <- aggregate(. ~  Species, data = castnumbers[,c(-1,-3)], FUN = var.na, na.action = na.pass) #[,-2]
  castvariance_logs <- aggregate(. ~  Species, data = castlogs[,c(-1,-3)], FUN = var.na, na.action = na.pass)
  castvariances[is.na(castvariances)] <- 0
  castvariance_logs[is.na(castvariance_logs)] <- 0
  castN <- aggregate(. ~  Species, data = castnumbers[,c(-1,-3)], length, na.action = na.pass) 
  castN = data.frame(castN$Species, rowMeans(castN[,-1])) #[,-2]
  names(castN) = c("Species", "N_specimens")
  castSE <- cbind(castvariances$Species, sqrt(castvariances[,-1])/sqrt(castN$N_specimens))
  castSE_logs <- cbind(castvariance_logs$Species, sqrt(castvariance_logs[,-1])/sqrt(castN[,-1]))
  names(castSE)[1] <- "Species"
  names(castSE_logs)[1] <- "Species"
```

## Introduction

0 -- PHYLOGENY
0.0 ML ribosomal marker phylogeny constrained by transcriptome tree with BS values at the nodes.
1 -- DESCRIPTIVE MORPHOLOGY AND EVOLUTIONARY HISTORY
1.0 Table showing for each species the mean, number of individuals measured, and standard error of every character, ordered by cnidomic index / tentillum size, and/or colored by clade.
1.05 Plate with all the tentillum diversity.
1.1 Table showing each character’s (illustrating the character per row)  the phylogenetic signal K with the p-value obtained by testing against 1000 simulated permutations, and the number of species included.
1.2 Table showing the best AICc supported model generating the data for each character and its AICc score. Model adequacy.
1.3 Table/figures showing the reconstructed ancestral values at the internal nodes of the phylogeny of characters with a supported phylogenetic model of evolution.
1.4 Figure showing major categorical character shifts, gains, and losses on a simplified phylogeny.
2 -- COMPARATIVE ANALYSES
2.0 Confusion matrix table showing PIC_correlations and trait correlation R2 and p-values for each pair of continuous characters. Confusion matrix for quantitative and categorical characters GLS. pGLS estimation of regression parameters in significantly correlated pairs.
2.1 Table showing the model parameters for each significant regression.
2.3 Verbally PCA and phylogenetic PCA/PICVarA_PCA of the characters. Phylomorphospace superimposed to the tip coordinates in PC1--PC2.
2.4 Table showing normalized rates of evolution for each character BAMM.
3 -- RELATIONSHIPS WITH DIET / FUNCTION / Hypothesis testing
3.0 Phylogeny with the tips mapped with the literature dietary associations, and internal nodes showing SIMMAP reconstructed states.
3.1 Table showing quantitative and categorical characters association effect size with each prey type in the diet.
3.2 Table showing the dAICc of OU model fitting versus white_noise and BM using reconstructed diets as regimes in a 16spp tree. Evaluate model adequacy of OU fits.
3.3 Interpret qualitatively the kinematic implications (high speed video) of the different regions of the morphospace.

Story: low dimensionality, cost-driven, dynamic specialization


## References

Siphonophores are... [@Mackie:1987uy].